# Generated by Django 5.0.6 on 2024-07-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_producto_categoria_alter_producto_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Carreras', 'Carreras'), ('Simulación', 'Simulación'), ('Acción', 'Acción'), ('Horror', 'Horror'), ('Aventura', 'Aventura'), ('Supervivencia', 'Supervivencia'), ('Sandbox', 'Sandbox'), ('Estrategia', 'Estrategia'), ('Party', 'Party'), ('Deportes', 'Deportes'), ('Rol', 'Rol')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento_subs',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
