# Generated by Django 5.0.6 on 2024-07-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_producto_categoria_alter_producto_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento_subs',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
