# Generated by Django 5.0.6 on 2024-07-05 10:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_producto_descuento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=0, max_digits=12)),
                ('estado_pedido', models.CharField(choices=[('Anulado', 'Anulado'), ('En proceso', 'En proceso'), ('Despachado', 'Despachado'), ('Entregado', 'Entregado'), ('Vendido', 'Vendido')], default='En proceso', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoEnBoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.boleta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
        migrations.AddField(
            model_name='boleta',
            name='productos',
            field=models.ManyToManyField(through='core.ProductoEnBoleta', to='core.producto'),
        ),
    ]
