# Generated by Django 5.0.6 on 2024-07-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_boleta_productoenboleta_boleta_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='imagen',
            field=models.ImageField(null=True, upload_to='perfil/'),
        ),
    ]
